module PrimeFactors (primeFactors) where


primeFactors :: Integer -> [Integer]
primeFactors n = factors n 2
  where
    factors n f
      | n < 2 = []
      | n `mod` f == 0 = f : factors (n `div` f) f
      | otherwise = factors n (f + 1)
--generated by copilot 

